language: python
python: 
  - "3.6"

services:
  - redis-server

addons:
  postgresql: "9.6"

install: 
  - pip install -r requirements.txt
  - pip install coveralls

before_script:
  - psql -c 'create database testdb;' -U postgres
  
script:
  - pytest
  - flake8

after_success:
  - coveralls
