version: '2'

services:
  database:
    restart: always
    image: postgres
    env_file:
      - .env
    ports:
      - "5433:5432"
    expose:
      - '5432'
  web:
    build: .
    volumes:
      - .:/apps
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - database